/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EditCountPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  charThreshold: 50,
  timeoutSeconds: 180
};
var EditCountPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.sessions = /* @__PURE__ */ new Map();
    this.timeoutId = null;
    this.currentFilePath = null;
    this.debouncedResetTimer = (0, import_obsidian.debounce)(() => {
      this.resetTimer();
    }, 1e3);
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new EditCountSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      this.startTrackingActiveFile();
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => {
        this.evaluateCurrentSession();
        this.startTrackingActiveFile();
      })
    );
    this.registerEvent(
      this.app.workspace.on(
        "editor-change",
        this.debouncedResetTimer
      )
    );
  }
  onunload() {
    this.evaluateCurrentSession();
    this.clearTimer();
    this.sessions.clear();
  }
  // --- Session lifecycle ---
  startTrackingActiveFile() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!(view == null ? void 0 : view.file)) {
      this.currentFilePath = null;
      this.clearTimer();
      return;
    }
    const path = view.file.path;
    this.currentFilePath = path;
    if (!this.sessions.has(path)) {
      const charCount = view.editor.getValue().length;
      this.sessions.set(path, {
        initialCharCount: charCount,
        evaluated: false
      });
    }
    this.resetTimer();
  }
  evaluateCurrentSession() {
    if (!this.currentFilePath)
      return;
    const session = this.sessions.get(this.currentFilePath);
    if (!session || session.evaluated)
      return;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!(view == null ? void 0 : view.file) || view.file.path !== this.currentFilePath) {
      const file = this.app.vault.getAbstractFileByPath(
        this.currentFilePath
      );
      if (file instanceof import_obsidian.TFile) {
        this.evaluateFromCache(file, session);
      }
      return;
    }
    const currentCharCount = view.editor.getValue().length;
    const diff = Math.abs(currentCharCount - session.initialCharCount);
    session.evaluated = true;
    this.sessions.delete(this.currentFilePath);
    this.clearTimer();
    if (diff >= this.settings.charThreshold) {
      this.incrementEditCount(view.file);
    }
  }
  async evaluateFromCache(file, session) {
    const content = await this.app.vault.cachedRead(file);
    const currentCharCount = content.length;
    const diff = Math.abs(currentCharCount - session.initialCharCount);
    session.evaluated = true;
    this.sessions.delete(file.path);
    if (diff >= this.settings.charThreshold) {
      this.incrementEditCount(file);
    }
  }
  // --- Timer management ---
  resetTimer() {
    this.clearTimer();
    this.timeoutId = setTimeout(() => {
      this.evaluateCurrentSession();
      this.startTrackingActiveFile();
    }, this.settings.timeoutSeconds * 1e3);
  }
  clearTimer() {
    if (this.timeoutId !== null) {
      clearTimeout(this.timeoutId);
      this.timeoutId = null;
    }
  }
  // --- Frontmatter update ---
  incrementEditCount(file) {
    this.app.fileManager.processFrontMatter(file, (fm) => {
      const current = typeof fm.edit_count === "number" ? fm.edit_count : 0;
      fm.edit_count = current + 1;
    });
  }
  // --- Settings ---
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var EditCountSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Character threshold").setDesc(
      "Minimum character count difference to count as a meaningful edit (default: 50)"
    ).addText(
      (text) => text.setPlaceholder("50").setValue(String(this.plugin.settings.charThreshold)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.charThreshold = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Inactivity timeout (seconds)").setDesc(
      "Time without edits before the session is evaluated (default: 180)"
    ).addText(
      (text) => text.setPlaceholder("180").setValue(
        String(this.plugin.settings.timeoutSeconds)
      ).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.timeoutSeconds = num;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};
